### ISSUE TITLE
Error with abstract-class.js

### ISSUE THREAD

**Issue by heartforit** [biggora/caminte#10]
Hello,

below of is a piece of code, please explain me what I'm doing wrong?
var caminte = require('caminte'),
    Schema = caminte.Schema,
    db = {
         driver     : "redis",
         host       : "localhost",
         port       : "6379"
    };
var schema = new Schema(db.driver, db);

var User = schema.define('User', {
    title:     { type: schema.String,  limit: 255 },
    fname:   { type: schema.String},
    lname:    { type: schema.String}
});
User.create({title: "dok", fname: "Max", lname: "Manus"}, function(err, data){
    console.log(err, data);
})

The error i get is:

****/caminte/lib/abstract-class.js:114
        if (BASE_TYPES.indexOf(type.name) === -1) {
                                   ^
TypeError: Cannot read property 'name' of undefined

How to fix this?

Best regards,
Mr. Love

**Comment by gaieges** [comment]
I also found that if you have entries **without types** in the schema, you'll get the same exception.  For example:

```
var User = schema.define('User', {
                       title    : { type: String, limit: 255 },
                       fname: { },
                       lname: { }
});
```

Ensure that there are 'type' objects in ```fname``` and ```lname``` and you won't get this exception.
