### ISSUE TITLE
How to create table corresponding to schema automatically ? 

### ISSUE THREAD

**Issue by alexandrevilain** [biggora/caminte#121]
I've made many schemas using caminte, but with postgres or sqlite tables are not created. Why ? 
Thank's,
Alexandre.

**Comment by tsega** [comment]
@alexandrevilain did you get a solution for this. I'm having the exact same problem.

**Comment by alexandrevilain** [comment]
Hello, 

No, I've switched to raw SQL. 

Alexandre.

**Comment by aryeharmon** [comment]
https://github.com/biggora/caminte/issues/128
