### ISSUE TITLE
Can i use it in production?

### ISSUE THREAD

**Issue by EmpireWorld** [biggora/caminte#141]
Can i use Caminte (and Caminte Express.js) in production?

**Comment by BKD-Digital** [comment]
IMO I wouldn't use any of the ORMs available for node or js. They're simply not anywhere near mature enough for production use.

We currently have a product that's on a LEMP stack and we were considering moving over to a node, express, mysql & reactjs stack but with the lack of mature ORMs for mysql we're simply going to stick with LEMP and use reactjs + redux for our view layer.

Sure, there's mongo but that's not the best tool for relational data.

**Comment by EmpireWorld** [comment]
Thanks. @BKD-Digital Why other node.js ORMs not available for production?

**Comment by OKNoah** [comment]
@EmpireWorld I'm not sure you should take that comment too seriously, I have not heard that before and successfully used many ORMs in production.

**Comment by EmpireWorld** [comment]
@OKNoah Most of the ORMs are in alpha and beta release they don;t filled the full release of 1.0.0 most of them are 0.1.2

Anyway, i will use them.

**Comment by OKNoah** [comment]
@EmpireWorld Sequelize and Mongoose are both in their 4th version.

**Comment by EmpireWorld** [comment]
@OKNoah I don't mean them, i mean ORMs like caminte, waterline, ... that they don't have any stable version.
