### ISSUE TITLE
All schema types

### ISSUE THREAD

**Issue by majimboo** [biggora/caminte#32]
what are all the schema types? Do you support Array of integers? Array of strings? Enum?
If yes, how?

**Comment by okor** [comment]
I find it rather surprising that caminte does not appear to support arrays. Any chance of an update or should this project be considered deprecated?

**Comment by biggora** [comment]
Hi,
I have a lot of work, and the module I develop in my spare time. 
So I do not always respond in time. 

for arrays use Json data type.

Schema data types list here
https://github.com/biggora/caminte/wiki/Schema-data-types
