### ISSUE TITLE
How select just some fields?

### ISSUE THREAD

**Issue by herlon214** [biggora/caminte#33]
Hello guys, I was looking for some way to select just some fields on my db.
I'm using MySQL, and my database has a field with big Text but I don't want to get it.

I was thinking about create 2 separated models, one with the big field an other without.

Anyone has any ideia about?

Thanks.

**Comment by biggora** [comment]
Hi,
select just some fields for `mysql` adapter:
```js
Post.all({
        fields: ['userId','name'.'email'],
        where: {userId: 2}, 
        order: 'id', 
        limit: 10, 
        skip: 20
    }, function(err, posts){
   // your code here
});
```

**Comment by foxdog05000** [comment]
Hello Guys ! And idea for select fields on postgresql ?
