### ISSUE TITLE
Promise support feature

### ISSUE THREAD

**Issue by marcominetti** [biggora/caminte#41]
Hi there, I'm going to implement support for Promise in my caminte fork and I''ll create pull request when ready. Is there any hints or idea from you?

**Comment by marcominetti** [comment]
@biggora Probably next week I'll work on this... do you have anything in your pipeline? Can I proceed and than create pull request when done?

**Comment by biggora** [comment]
Hi
I'm not planning to work in this direction. If you do this, I'll be grateful to you.
Thank you.

**Comment by kokujin** [comment]
What is the status on this?

**Comment by marcominetti** [comment]
Sorry, I've switched to loopback, similar API and source (juggling-db) but with much more features and backed by strongloop (ibm). I mean loopback used programmatically as loopback-datasource-juggler npm package.

**Comment by stanleyxu2005** [comment]
There is some "promisify" tool like bluebird which can change sync functions to promise pattern.

**Comment by nervgh** [comment]
I use **caminte** with [Koa](https://github.com/koajs/koa) which supports [Generators](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator). My simple solution is Hook class:

```js

// Glue for callbacks, promises & generators
class Hook {

  constructor() {
    let deferred = {};
    this.promise = new Promise((resolve, reject) => {
      deferred.resolve = resolve;
      deferred.reject = reject;
    });
    this.callback = this.constructor.callback.bind(null, deferred);
  }

  static callback(deferred, error, response) {
    if (error) {
      deferred.reject(error);
      return;
    }
    deferred.resolve(response);
  }
}

// ------------------
// Usage
// ------------------

app.use(function*() {
  let hook = new Hook(); // (1)
  let query = Model.all(); // Model is caminte model
  query.order('modifiedDate DESC');
  query.run(hook.callback); // (2)
  let record = yield hook.promise; // (3)
  this.render('news/details', record);
});
```
