### ISSUE TITLE
MongoDB driver 2.0

### ISSUE THREAD

**Issue by ramiel** [biggora/caminte#48]
The current adapter dosen't work with new mongodb driver. I indexed a couple of problems and, if nobody is already working on it, I could write a new adapter.

Let me know

**Comment by dodoqumy** [comment]
er, we made 4 patches on this adapter in our project.
But I am ashamed of sharing it here, but it worked good in our project.

Wish caminte keeping pace with the times

from china

**Comment by syda** [comment]
Anyone looking into this? I cant make mongodb driver to work although mongoose seems to work

**Comment by fmsouza** [comment]
I'm trying it since yesterday but I can't manage to make it retrieve data from mongodb...

**Comment by biggora** [comment]
Fixed MongoDB adapter for driver 2.0
