### ISSUE TITLE
Still Need Custom Query

### ISSUE THREAD

**Issue by emman-ok** [biggora/caminte#69]
it will be nice to add custom sql command query execution.

**Comment by biggora** [comment]
Hi,
in mysql, sqlite3 and postgres adapters for this case available two ways
```js
Model.query(sql,callback);
```
or
```js
Model.schema.client.query(sql,callback);
```

**Comment by emman-ok** [comment]
Thanks Very Much..

**Comment by hungn85** [comment]
Thanks so much

**Comment by ritvick** [comment]
How can I execute queries without specifying model. 
Lets say I am inputing queries from a user of my portal, and I just want to execute that query with connection / schema object. I do not know how the user would have modeled the schema.
