### ISSUE TITLE
.update() not returning my object

### ISSUE THREAD

**Issue by ellisio** [biggora/caminte#91]
Hello,

I am using Redis. Below is my model's definition.

```
var Caller = schema.define('Caller', {
    socket: { type: schema.String, index: true },
    room: { type: schema.String, index: true },
    call_id: { type: schema.String, index: true },
    name: schema.String,
    email: schema.String,
    number: schema.String,
    avatar: schema.String,
    location: schema.String,
    organizer: schema.Boolean,
    host: schema.Boolean,
    connected: schema.Boolean,
    holding: schema.Boolean,
    muted: schema.Boolean,
    hand_raised: schema.Boolean
});
```

When I run the following code, I receive `null` for the `err` parameter, and `undefined` for the `caller` parameter. However, the changes are updating in Redis correctly.

```
var callId = "caller-id-here";

Caller.update({
    where: {
        call_id: callId
    }
}, {
    holding: flag
}, function (err, caller) {
    console.log(err, caller);
});
```

Any idea why this would be happening?

Cheers,
Andrew

**Comment by eliascodes** [comment]
The redis adapter does not return the affected model. See [here](https://github.com/biggora/caminte/blob/master/lib/adapters/redis.js#L389-L396)

**Comment by biggora** [comment]
Hi,
yes, it truth because `update` method supports change more then one row. To return all affected rows in callback may bring problem with performance.

for update single instance use example below:
```js
   Caller.all({
       call_id: callId
   }, function(err, caller){
        caller.updateAttributes( { holding: flag }, function (err) {
             // some code here
        });
   });
```
