### ISSUE TITLE
Defined relations are not working

### ISSUE THREAD

**Issue by drajvver** [biggora/caminte#94]
I was trying to use this library with very simple MySQL db, with 4 tables and a few relations. I've defined a one-to-many relation 
`Clients.hasMany(Projects, { as: 'projects', foreignKey: 'ClientId' });`
but after trying to fetch projects
`Clients.projects(function (err, users) {
        res.send(JSON.stringify(users));
    });`

I get an error saying that "projects" is not a function. Any ideas?

**Comment by eliascodes** [comment]
Setting up relations only adds methods to the *instance* (i.e. when you do `const client = new Client()`)

If you just want all projects, why not do
```
Projects.all(function (err, projects) ....)
```

If you want the projects of a specific client, you need to find that client first:
```
Clients.findOne({where: { <some query> }}, function (err, client) {
  client.projects.all(function (err, projects) {
    // do something
  })
})
```
